# SPDX-FileCopyrightText: 2025 GitHub
# SPDX-License-Identifier: MIT

seclab-taskflow-agent:
  version: 1
  filetype: model_config
models:
   code_analysis: gpt-4.1-mini
   general_tasks: gpt-4.1-mini
