# SPDX-FileCopyrightText: GitHub, Inc.
# SPDX-License-Identifier: MIT

seclab-taskflow-agent:
  version: "1.0"
  filetype: model_config
models:
   code_analysis: gpt-5-mini
   general_tasks: gpt-5-mini
